# fly.toml file generated for divine-lake-5351 on 2023-03-05T16:28:29Z

app = "divine-lake-5351"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
RAILS_ENV="production"
RAILS_SERVE_STATIC_FILES="true"
RAILS_LOG_TO_STDOUT="true"
RAILS_MAX_THREADS="5"
DATABASE_URL="postgresql://user:password@hostname/dbname"
RAILS_DB_POOL="2"
RAILS_MASTER_KEY="c7a51147ddabd391197b5a051c53d95feca4e8e57a0e0830d3bbdce9cfc979f0ba8bd4a4632d96666d5bd47aa9dada691196303ae06ca98991ccde2b543a34a8"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
